package main

import (
	"encoding/json"
	"fmt"
	"os"
	"testing"
)

// Conformance suite: replays the frozen cases generated by the Python oracle
// (emu/conformance.json) through the Go CPU and asserts identical outputs. This
// is the contract the Go port must satisfy — `go test` instead of ad-hoc runs.

const conformancePath = "../emu/conformance.json"

type cState struct {
	Pc, Sr               uint32
	R                    []uint32
	Rbank1               []uint32
	Pr, Gbr, Vbr         uint32
	Ssr, Spc, Mach, Macl uint32
	Data                 map[string]uint32
}

type cSetup struct {
	R                                          []uint32
	Rbank1                                     []uint32
	Sr, Pr, Gbr, Vbr, Ssr, Spc, Mach, Macl     uint32
	Fpul, Fpscr                                uint32
}

type cCase struct {
	Name   string
	Code   []uint32
	Steps  int
	Setup  cSetup
	Data   map[string]uint32
	Check  []uint32
	Irq    []uint32
	Pc     uint32
	Expect cState
}

func atou(s string) uint32 {
	var v uint64
	fmt.Sscanf(s, "%d", &v)
	return uint32(v)
}

func replayGo(c *cCase) (cState, string) {
	mmio := NewMMIOBus()
	mem := NewMemory([]byte{}, mmio)
	cpu := NewCPU(mem)
	// set architectural state directly (active bank as given)
	for i := 0; i < 16 && i < len(c.Setup.R); i++ {
		cpu.r[i] = c.Setup.R[i]
	}
	for i := 0; i < 8 && i < len(c.Setup.Rbank1); i++ {
		cpu.rbank1[i] = c.Setup.Rbank1[i]
	}
	cpu.sr = c.Setup.Sr
	cpu.pr, cpu.gbr, cpu.vbr = c.Setup.Pr, c.Setup.Gbr, c.Setup.Vbr
	cpu.ssr, cpu.spc = c.Setup.Ssr, c.Setup.Spc
	cpu.mach, cpu.macl = c.Setup.Mach, c.Setup.Macl
	cpu.fpul, cpu.fpscr = c.Setup.Fpul, c.Setup.Fpscr

	for i, opc := range c.Code {
		mem.W16(c.Pc+uint32(2*i), opc)
	}
	for addr, val := range c.Data {
		mem.W32(atou(addr), val)
	}
	if len(c.Irq) == 2 {
		cpu.raiseIRQ(c.Irq[0], c.Irq[1])
	}
	cpu.cycles = 0
	cpu.pc = c.Pc

	panicMsg := ""
	func() {
		defer func() {
			if r := recover(); r != nil {
				panicMsg = fmt.Sprintf("panic: %v", r)
			}
		}()
		for i := 0; i < c.Steps; i++ {
			cpu.step()
		}
	}()

	data := map[string]uint32{}
	for _, a := range c.Check {
		data[fmt.Sprintf("%d", a)] = mem.R32(a)
	}
	st := cState{
		Pc: cpu.pc, Sr: cpu.sr,
		R:      append([]uint32{}, cpu.r[:]...),
		Rbank1: append([]uint32{}, cpu.rbank1[:]...),
		Pr:     cpu.pr, Gbr: cpu.gbr, Vbr: cpu.vbr,
		Ssr: cpu.ssr, Spc: cpu.spc, Mach: cpu.mach, Macl: cpu.macl,
		Data: data,
	}
	return st, panicMsg
}

func TestConformance(t *testing.T) {
	raw, err := os.ReadFile(conformancePath)
	if err != nil {
		t.Skipf("no conformance.json (%v) — run: python emu/conformance_gen.py", err)
	}
	var doc struct {
		Cases []cCase
	}
	if err := json.Unmarshal(raw, &doc); err != nil {
		t.Fatalf("parse conformance.json: %v", err)
	}
	if len(doc.Cases) == 0 {
		t.Fatal("no cases")
	}
	fails := 0
	for i := range doc.Cases {
		c := &doc.Cases[i]
		got, pmsg := replayGo(c)
		if pmsg != "" {
			t.Errorf("%s: %s", c.Name, pmsg)
			fails++
			continue
		}
		if msg := diff(c.Name, &c.Expect, &got); msg != "" {
			t.Errorf("%s", msg)
			fails++
		}
	}
	t.Logf("%d/%d conformance cases pass", len(doc.Cases)-fails, len(doc.Cases))
}

func diff(name string, want, got *cState) string {
	out := ""
	add := func(field string, w, g uint32) {
		if w != g {
			out += fmt.Sprintf("\n  %s: got 0x%08x want 0x%08x", field, g, w)
		}
	}
	add("pc", want.Pc, got.Pc)
	add("sr", want.Sr, got.Sr)
	for i := 0; i < 16; i++ {
		add(fmt.Sprintf("r%d", i), want.R[i], got.R[i])
	}
	for i := 0; i < 8; i++ {
		add(fmt.Sprintf("rbank1[%d]", i), want.Rbank1[i], got.Rbank1[i])
	}
	add("pr", want.Pr, got.Pr)
	add("gbr", want.Gbr, got.Gbr)
	add("vbr", want.Vbr, got.Vbr)
	add("ssr", want.Ssr, got.Ssr)
	add("spc", want.Spc, got.Spc)
	add("mach", want.Mach, got.Mach)
	add("macl", want.Macl, got.Macl)
	for k, w := range want.Data {
		add("mem["+k+"]", w, got.Data[k])
	}
	if out != "" {
		return "CONFORMANCE FAIL " + name + out
	}
	return ""
}
